---
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tarball: ${{ steps.pack.outputs.tarball }}
    steps:
      - uses: textbook/take-action@nodejs
        with:
          node-version: "22"
      - run: npm run lint
      - run: npm run test:cover
      - run: npm run build
      - run: |
          echo "tarball=$(npm --workspace check-engine-light pack)" >> "$GITHUB_OUTPUT"
        id: pack
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.pack.outputs.tarball }}
          if-no-files-found: error
  test:
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        node: [ "20.11", "20", "22", "24" ]
        platform: [ ubuntu ]
        include:
          - node: "22"
            platform: "windows"
          - node: "22"
            platform: "macos"
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - uses: textbook/take-action@nodejs
        with:
          checkout: false
          node-version: ${{ matrix.node }}
      - uses: actions/download-artifact@v4
        with:
          name: package
      - run: |
          npm init --yes
          npm pkg set 'engines.node=^22'
          npm install ${{ needs.build.outputs.tarball }}
          npx check-engine-light .
